services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony

  nginx:
    image: nginx:stable
    container_name: symfony_nginx
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"
    networks:
      - symfony
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.symfony.rule=Host(`taxi-paris.tomremili.fr`)"
      - "traefik.http.routers.symfony.entrypoints=websecure"
      - "traefik.http.routers.symfony.tls=true"
        # Pas besoin de let's encrypt -> CLOUDFLARE  Https
        #- "traefik.http.routers.symfony.tls.certresolver=le"
      - "traefik.http.services.symfony.loadbalancer.server.port=80"

  mailpit:
    image: axllent/mailpit
    container_name: symfony_mailpit
    networks:
      - symfony
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  symfony:
    name: symfony
  web:
    external: true