services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=dev
    networks:
      - symfony

  nginx:
    image: nginx:stable
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - symfony

  mailpit:
    image: axllent/mailpit
    container_name: symfony_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - symfony

networks:
  symfony:
